# Generated by Django 6.0.3 on 2026-03-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('testimonial_type', models.CharField(choices=[('student', 'Student'), ('guardian', 'Guardian'), ('topper', 'Topper'), ('alumni', 'Alumni')], default='student', max_length=20)),
                ('batch_year', models.CharField(blank=True, max_length=10)),
                ('program', models.CharField(blank=True, max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('message', models.TextField()),
                ('rank', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-batch_year'],
            },
        ),
    ]
